apiVersion: v1
kind: Service
metadata:
  name: institucional-web-svc
spec:
  type: NodePort
  selector:
    app: institucional-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
