apiVersion: apps/v1
kind: Deployment
metadata:
  name: institucional-web
  labels:
    app: institucional-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: institucional-nginx
  template:
    metadata:
      labels:
        app: institucional-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volumen-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: volumen-html
          persistentVolumeClaim:
            claimName: institucional-web-pvc
